import React, { Component } from 'react'
import { ContractData } from 'drizzle-react-components'
import Petitions from '../petition/petitions/Petitions.js'
import PetitionForm from '../petition/petition-form/PetitionForm.js'
import './Home.css'


class Home extends Component {

  render() {
    return (
      <div>
        <main className="site-wrap">
          <div className='home-title'>
            <h1 className="main-header">Finally! Decentralized* Tarot Readings!</h1>
            <label>*kinda</label><br/>
            <button className="make-petition">Make Petition</button>
          </div>
          <div className="latest-petitions">
            <h1>Latest:</h1>
            <Petitions method="getLastPetitions"/>
          </div>
          <div className="how-works">
            <h1>How it works:</h1>
            <h1>Step 1: Make a Petition</h1>
            <p>Here you can specify what topics you're interested in visiting upong your reading, add any comments you may like to contextualize your needs and specify which service you'd like to have your video reading hosted on.
              Crucially in this step you'll upload the petition to the TAROeTh smart contract and introduce your own influence in the web of Causality that will finally result in your reading. (Akin to picking out your own cards in a live reading)
              You will see the cards in your reading immediatly.
            </p>
            <p>You may include an ETH incentive to make sure you're petitition gets speedy attention and to support this service, it is purely optional however.</p>

            <h1>Step 2a: I get around to it</h1>
            <p>
              Harnessing the overpowering memetic miasma generated by blockchain transactions and cryptocurrency in general I record a Tarot card interpretation taking into consideration the specifications of your petition and the cards your foray into decentralized computing produced.
            </p>

            <h1>Step 2b: I don't get around to it</h1>
            <p>
              I get very busy and don't get around to recording an interpretation for your reading. It happens and you shouldn't suffer for it. If a week has passed since your petition was made you can cancel it and get your ETH incentive back. (If you didn't give any, then what do you care if I don't get around to it?)
            </p>
          </div>
        </main>
      </div>
    )
  }
}

export default Home
